#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the surfaceArea function below.
def TopAndBottom(A):
    area = 0
    for x in A:
        for y in x:
            if y != 0:
                area += 1
    area = area*2
    return area

def LeftAndRight(A):
    area = 0
    for x in A:
        temp = 0
        for y in x:
            if y >= temp:
                area += y-temp
                temp = y
            else:
                temp = y
    area = area*2
    return area

def FrontAndBack(A):
    r = len(A)
    c = len(A[0])
    B = [[0 for x in range(r)] for y in range(c)]
    for i in range(c): 
        for j in range(r): 
            B[i][j] = A[j][i] 
    area = LeftAndRight(B)
    return area

def surfaceArea(A):
    result = TopAndBottom(A)+LeftAndRight(A)+FrontAndBack(A)
    return result

    


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    HW = input().split()

    H = int(HW[0])

    W = int(HW[1])

    A = []

    for _ in range(H):
        A.append(list(map(int, input().rstrip().split())))

    result = surfaceArea(A)

    fptr.write(str(result) + '\n')

    fptr.close()
